packages:
  - admin-web
  - packages/*

allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  core-js-pure: true
  esbuild: true
  protobufjs: true
  sharp: true
  weapp-tailwindcss: true

minimumReleaseAgeExclude:
  - '@tanstack/query-core@5.102.8'
  - '@tanstack/react-query@5.102.8'
  - '@testing-library/react@16.3.3'
  - '@vitejs/plugin-react@6.1.1'
