-- M03: Event feedback export — no DDL to roll back.
--
-- The forward migration 072 made no schema changes. Feedback data continues
-- to be stored in mip_event_feedback.answers_json. Nothing to undo.
