export const defaults = {
  appNamespace: 'mip',
  touristAppId: 'touristappid',
  identityFunctionName: 'mip-identity-api',
  mediaFunctionName: 'mip-media-api',
  eventsFunctionName: 'mip-events-api',
  opportunitiesFunctionName: 'mip-opportunities-api',
  communityFunctionName: 'mip-community-api',
  commerceFunctionName: 'mip-commerce-api',
  adminFunctionName: 'mip-admin-api',
  growthFunctionName: 'mip-growth-api',
  aiFunctionName: 'mip-ai-api',
  notificationsFunctionName: 'mip-notifications-api',
  paymentFunctionName: 'mip-cloudpay',
  paymentCallbackFunctionName: 'mip-cloudpay-callback',
  ledgerFunctionName: 'mip-payment-ledger',
  paymentMode: 'disabled',
  catalogStage: 'TEST',
} as const
