// figma 2215_4618 选择城市：静态全国城市目录 + 拼音检索，按首字母分组浏览。
// 城市标签 id 不在此维护——由服务端城市标签库（catalog.cityTags）按 label 解析，
// 页面只提交所选城市（REQUIREMENTS.md：页面只提交意图，资格与字典由服务端决定）。

export interface CityDirectoryEntry {
  label: string
  pinyin: string
}

// 设计稿热门城市网格（编辑页快捷标签取前 8 个）。
export const HOT_CITY_LABELS = [
  '北京',
  '上海',
  '广州',
  '深圳',
  '杭州',
  '天津',
  '西安',
  '苏州',
  '武汉',
  '厦门',
  '长沙',
  '成都',
  '郑州',
  '重庆',
] as const

export const EDITOR_HOT_CITY_COUNT = 8

export const CITY_DIRECTORY: CityDirectoryEntry[] = [
  { label: '阿坝', pinyin: 'aba' },
  { label: '阿克苏地区', pinyin: 'akesudiqu' },
  { label: '阿拉尔', pinyin: 'alaer' },
  { label: '阿拉善盟', pinyin: 'alashanmeng' },
  { label: '阿勒泰地区', pinyin: 'aletaidiqu' },
  { label: '阿里地区', pinyin: 'alidiqu' },
  { label: '阿尔山', pinyin: 'aershan' },
  { label: '阿图什', pinyin: 'atushi' },
  { label: '鞍山', pinyin: 'anshan' },
  { label: '安庆', pinyin: 'anqing' },
  { label: '安康', pinyin: 'ankang' },
  { label: '安顺', pinyin: 'anshun' },
  { label: '安阳', pinyin: 'anyang' },
  { label: '澳门', pinyin: 'aomen' },
  { label: '白城', pinyin: 'baicheng' },
  { label: '白山', pinyin: 'baishan' },
  { label: '白银', pinyin: 'baiyin' },
  { label: '百色', pinyin: 'baise' },
  { label: '蚌埠', pinyin: 'bengbu' },
  { label: '保定', pinyin: 'baoding' },
  { label: '包头', pinyin: 'baotou' },
  { label: '巴彦淖尔', pinyin: 'bayannaoer' },
  { label: '巴中', pinyin: 'bazhong' },
  { label: '宝鸡', pinyin: 'baoji' },
  { label: '保山', pinyin: 'baoshan' },
  { label: '北屯', pinyin: 'beitun' },
  { label: '北海', pinyin: 'beihai' },
  { label: '北京', pinyin: 'beijing' },
  { label: '本溪', pinyin: 'benxi' },
  { label: '毕节', pinyin: 'bijie' },
  { label: '滨州', pinyin: 'binzhou' },
  { label: '亳州', pinyin: 'bozhou' },
  { label: '成都', pinyin: 'chengdu' },
  { label: '常德', pinyin: 'changde' },
  { label: '昌吉', pinyin: 'changji' },
  { label: '长春', pinyin: 'changchun' },
  { label: '常熟', pinyin: 'changshu' },
  { label: '长沙', pinyin: 'changsha' },
  { label: '长治', pinyin: 'changzhi' },
  { label: '常州', pinyin: 'changzhou' },
  { label: '潮州', pinyin: 'chaozhou' },
  { label: '承德', pinyin: 'chengde' },
  { label: '沧州', pinyin: 'cangzhou' },
  { label: '朝阳', pinyin: 'chaoyang' },
  { label: '崇左', pinyin: 'chongzuo' },
  { label: '滁州', pinyin: 'chuzhou' },
  { label: '楚雄', pinyin: 'chuxiong' },
  { label: '池州', pinyin: 'chizhou' },
  { label: '郴州', pinyin: 'chenzhou' },
  { label: '重庆', pinyin: 'chongqing' },
  { label: '大连', pinyin: 'dalian' },
  { label: '丹东', pinyin: 'dandong' },
  { label: '大同', pinyin: 'datong' },
  { label: '大理', pinyin: 'dali' },
  { label: '达州', pinyin: 'dazhou' },
  { label: '德州', pinyin: 'dezhou' },
  { label: '大庆', pinyin: 'daqing' },
  { label: '德阳', pinyin: 'deyang' },
  { label: '德宏', pinyin: 'dehong' },
  { label: '定西', pinyin: 'dingxi' },
  { label: '迪庆', pinyin: 'diqing' },
  { label: '东营', pinyin: 'dongying' },
  { label: '东莞', pinyin: 'dongguan' },
  { label: '大兴安岭', pinyin: 'daxinganling' },
  { label: '鄂尔多斯', pinyin: 'eerduosi' },
  { label: '鄂州', pinyin: 'ezhou' },
  { label: '恩施', pinyin: 'enshi' },
  { label: '防城港', pinyin: 'fangchenggang' },
  { label: '佛山', pinyin: 'foshan' },
  { label: '抚顺', pinyin: 'fushun' },
  { label: '阜新', pinyin: 'fuxin' },
  { label: '阜阳', pinyin: 'fuyang' },
  { label: '福州', pinyin: 'fuzhou' },
  { label: '抚州', pinyin: 'fuzhou' },
  { label: '广州', pinyin: 'guangzhou' },
  { label: '高雄', pinyin: 'gaoxiong' },
  { label: '赣州', pinyin: 'ganzhou' },
  { label: '广元', pinyin: 'guangyuan' },
  { label: '广安', pinyin: 'guangan' },
  { label: '贵港', pinyin: 'guigang' },
  { label: '桂林', pinyin: 'guilin' },
  { label: '贵阳', pinyin: 'guiyang' },
  { label: '果洛', pinyin: 'guoluo' },
  { label: '甘南', pinyin: 'gannan' },
  { label: '临夏', pinyin: 'linxia' },
  { label: '合作', pinyin: 'hezuo' },
  { label: '固原', pinyin: 'guyuan' },
  { label: '哈尔滨', pinyin: 'haerbin' },
  { label: '海北', pinyin: 'haibei' },
  { label: '海东', pinyin: 'haidong' },
  { label: '海口', pinyin: 'haikou' },
  { label: '海西', pinyin: 'haixi' },
  { label: '邯郸', pinyin: 'handan' },
  { label: '汉中', pinyin: 'hanzhong' },
  { label: '鹤壁', pinyin: 'hebi' },
  { label: '河池', pinyin: 'hechi' },
  { label: '合肥', pinyin: 'hefei' },
  { label: '杭州', pinyin: 'hangzhou' },
  { label: '鹤岗', pinyin: 'hegang' },
  { label: '黑河', pinyin: 'heihe' },
  { label: '衡水', pinyin: 'hengshui' },
  { label: '衡阳', pinyin: 'hengyang' },
  { label: '怀化', pinyin: 'huaihua' },
  { label: '和田地区', pinyin: 'hetiandiqu' },
  { label: '呼伦贝尔', pinyin: 'hulunbeier' },
  { label: '葫芦岛', pinyin: 'huludao' },
  { label: '哈密', pinyin: 'hami' },
  { label: '淮安', pinyin: 'huaian' },
  { label: '淮北', pinyin: 'huaibei' },
  { label: '淮南', pinyin: 'huainan' },
  { label: '黄冈', pinyin: 'huanggang' },
  { label: '黄南', pinyin: 'huangnan' },
  { label: '黄山', pinyin: 'huangshan' },
  { label: '黄石', pinyin: 'huangshi' },
  { label: '惠州', pinyin: 'huizhou' },
  { label: '菏泽', pinyin: 'heze' },
  { label: '河源', pinyin: 'heyuan' },
  { label: '呼和浩特', pinyin: 'huhehaote' },
  { label: '湖州', pinyin: 'huzhou' },
  { label: '佳木斯', pinyin: 'jiamusi' },
  { label: '吉安', pinyin: 'ji\'an' },
  { label: '江门', pinyin: 'jiangmen' },
  { label: '揭阳', pinyin: 'jieyang' },
  { label: '济南', pinyin: 'jinan' },
  { label: '金昌', pinyin: 'jinchang' },
  { label: '金华', pinyin: 'jinhua' },
  { label: '济宁', pinyin: 'jining' },
  { label: '晋城', pinyin: 'jincheng' },
  { label: '晋中', pinyin: 'jinzhong' },
  { label: '焦作', pinyin: 'jiaozuo' },
  { label: '锦州', pinyin: 'jinzhou' },
  { label: '景德镇', pinyin: 'jingdezhen' },
  { label: '荆门', pinyin: 'jingmen' },
  { label: '荆州', pinyin: 'jingzhou' },
  { label: '嘉兴', pinyin: 'jiaxing' },
  { label: '嘉峪关', pinyin: 'jiayuguan' },
  { label: '吉林', pinyin: 'jilin' },
  { label: '九江', pinyin: 'jiujiang' },
  { label: '酒泉', pinyin: 'jiuquan' },
  { label: '鸡西', pinyin: 'jixi' },
  { label: '开封', pinyin: 'kaifeng' },
  { label: '昆明', pinyin: 'kunming' },
  { label: '克拉玛依', pinyin: 'kelamayi' },
  { label: '喀什', pinyin: 'kashi' },
  { label: '库尔勒', pinyin: 'kuerle' },
  { label: '克孜勒苏', pinyin: 'kezilesu' },
  { label: '拉萨', pinyin: 'lasa' },
  { label: '乐山', pinyin: 'leshan' },
  { label: '兰州', pinyin: 'lanzhou' },
  { label: '丽江', pinyin: 'lijiang' },
  { label: '临汾', pinyin: 'linfen' },
  { label: '临沧', pinyin: 'lincang' },
  { label: '廊坊', pinyin: 'langfang' },
  { label: '来宾', pinyin: 'laibin' },
  { label: '临沂', pinyin: 'linyi' },
  { label: '聊城', pinyin: 'liaocheng' },
  { label: '林芝', pinyin: 'linzhi' },
  { label: '丽水', pinyin: 'lishui' },
  { label: '六盘水', pinyin: 'liupanshui' },
  { label: '柳州', pinyin: 'liuzhou' },
  { label: '陇南', pinyin: 'longnan' },
  { label: '六安', pinyin: 'lu\'an' },
  { label: '龙岩', pinyin: 'longyan' },
  { label: '洛阳', pinyin: 'luoyang' },
  { label: '泸州', pinyin: 'luzhou' },
  { label: '漯河', pinyin: 'luohe' },
  { label: '娄底', pinyin: 'loudi' },
  { label: '吕梁', pinyin: 'lvliang' },
  { label: '马鞍山', pinyin: 'maanshan' },
  { label: '茂名', pinyin: 'maoming' },
  { label: '眉山', pinyin: 'meishan' },
  { label: '梅州', pinyin: 'meizhou' },
  { label: '绵阳', pinyin: 'mianyang' },
  { label: '牡丹江', pinyin: 'mudanjiang' },
  { label: '满洲里', pinyin: 'manzhouli' },
  { label: '南昌', pinyin: 'nanchang' },
  { label: '南充', pinyin: 'nanchong' },
  { label: '南宁', pinyin: 'nanning' },
  { label: '南京', pinyin: 'nanjing' },
  { label: '南通', pinyin: 'nantong' },
  { label: '南阳', pinyin: 'nanyang' },
  { label: '那曲', pinyin: 'naqu' },
  { label: '内江', pinyin: 'neijiang' },
  { label: '南平', pinyin: 'nanping' },
  { label: '宁波', pinyin: 'ningbo' },
  { label: '宁德', pinyin: 'ningde' },
  { label: '怒江', pinyin: 'nujiang' },
  { label: '盘锦', pinyin: 'panjin' },
  { label: '攀枝花', pinyin: 'panzhihua' },
  { label: '平顶山', pinyin: 'pingdingshan' },
  { label: '平凉', pinyin: 'pingliang' },
  { label: '萍乡', pinyin: 'pingxiang' },
  { label: '普洱', pinyin: 'puer' },
  { label: '莆田', pinyin: 'putian' },
  { label: '青岛', pinyin: 'qingdao' },
  { label: '庆阳', pinyin: 'qingyang' },
  { label: '清远', pinyin: 'qingyuan' },
  { label: '衢州', pinyin: 'quzhou' },
  { label: '秦皇岛', pinyin: 'qinhuangdao' },
  { label: '钦州', pinyin: 'qinzhou' },
  { label: '齐齐哈尔', pinyin: 'qiqihaer' },
  { label: '泉州', pinyin: 'quanzhou' },
  { label: '曲靖', pinyin: 'qujing' },
  { label: '七台河', pinyin: 'qitaihe' },
  { label: '黔东南', pinyin: 'qiandongnan' },
  { label: '黔南', pinyin: 'qiannan' },
  { label: '黔西南', pinyin: 'qianxinan' },
  { label: '日喀则', pinyin: 'rikaze' },
  { label: '日照', pinyin: 'rizhao' },
  { label: '上海', pinyin: 'shanghai' },
  { label: '三门峡', pinyin: 'sanmenxia' },
  { label: '三明', pinyin: 'sanming' },
  { label: '三亚', pinyin: 'sanya' },
  { label: '商洛', pinyin: 'shangluo' },
  { label: '商丘', pinyin: 'shangqiu' },
  { label: '邵阳', pinyin: 'shaoyang' },
  { label: '上饶', pinyin: 'shangrao' },
  { label: '山南', pinyin: 'shannan' },
  { label: '汕头', pinyin: 'shantou' },
  { label: '汕尾', pinyin: 'shanwei' },
  { label: '韶关', pinyin: 'shaoguan' },
  { label: '绍兴', pinyin: 'shaoxing' },
  { label: '深圳', pinyin: 'shenzhen' },
  { label: '沈阳', pinyin: 'shenyang' },
  { label: '石河子', pinyin: 'shihezi' },
  { label: '石家庄', pinyin: 'shijiazhuang' },
  { label: '石嘴山', pinyin: 'shizuishan' },
  { label: '十堰', pinyin: 'shiyan' },
  { label: '双鸭山', pinyin: 'shuangyashan' },
  { label: '朔州', pinyin: 'shuozhou' },
  { label: '四平', pinyin: 'siping' },
  { label: '松原', pinyin: 'songyuan' },
  { label: '宿迁', pinyin: 'suqian' },
  { label: '宿州', pinyin: 'suzhou' },
  { label: '绥化', pinyin: 'suihua' },
  { label: '随州', pinyin: 'suizhou' },
  { label: '遂宁', pinyin: 'suining' },
  { label: '苏州', pinyin: 'suzhou' },
  { label: '塔城地区', pinyin: 'tachengdiqu' },
  { label: '太原', pinyin: 'taiyuan' },
  { label: '泰安', pinyin: 'taian' },
  { label: '台北', pinyin: 'taibei' },
  { label: '台中', pinyin: 'taizhong' },
  { label: '台南', pinyin: 'tainan' },
  { label: '台州', pinyin: 'taizhou' },
  { label: '泰州', pinyin: 'taizhou' },
  { label: '唐山', pinyin: 'tangshan' },
  { label: '天津', pinyin: 'tianjin' },
  { label: '天水', pinyin: 'tianshui' },
  { label: '铁岭', pinyin: 'tieling' },
  { label: '铜川', pinyin: 'tongchuan' },
  { label: '通化', pinyin: 'tonghua' },
  { label: '通辽', pinyin: 'tongliao' },
  { label: '铜陵', pinyin: 'tongling' },
  { label: '铜仁', pinyin: 'tongren' },
  { label: '吐鲁番', pinyin: 'tulufan' },
  { label: '威海', pinyin: 'weihai' },
  { label: '潍坊', pinyin: 'weifang' },
  { label: '温州', pinyin: 'wenzhou' },
  { label: '乌海', pinyin: 'wuhai' },
  { label: '芜湖', pinyin: 'wuhu' },
  { label: '武汉', pinyin: 'wuhan' },
  { label: '武威', pinyin: 'wuwei' },
  { label: '渭南', pinyin: 'weinan' },
  { label: '无锡', pinyin: 'wuxi' },
  { label: '吴忠', pinyin: 'wuzhong' },
  { label: '梧州', pinyin: 'wuzhou' },
  { label: '乌鲁木齐', pinyin: 'wulumuqi' },
  { label: '五家渠', pinyin: 'wujiaqu' },
  { label: '文山', pinyin: 'wenshan' },
  { label: '乌兰察布', pinyin: 'wulanchabu' },
  { label: '西安', pinyin: 'xian' },
  { label: '厦门', pinyin: 'xiamen' },
  { label: '湘潭', pinyin: 'xiangtan' },
  { label: '湘西', pinyin: 'xiangxi' },
  { label: '襄阳', pinyin: 'xiangyang' },
  { label: '咸宁', pinyin: 'xianning' },
  { label: '咸阳', pinyin: 'xianyang' },
  { label: '孝感', pinyin: 'xiaogan' },
  { label: '锡林郭勒盟', pinyin: 'xilinguolemeng' },
  { label: '兴安盟', pinyin: 'xinganmeng' },
  { label: '邢台', pinyin: 'xingtai' },
  { label: '西宁', pinyin: 'xining' },
  { label: '新乡', pinyin: 'xinxiang' },
  { label: '新余', pinyin: 'xinyu' },
  { label: '信阳', pinyin: 'xinyang' },
  { label: '忻州', pinyin: 'xinzhou' },
  { label: '西双版纳', pinyin: 'xishuangbanna' },
  { label: '宣城', pinyin: 'xuancheng' },
  { label: '许昌', pinyin: 'xuchang' },
  { label: '徐州', pinyin: 'xuzhou' },
  { label: '香港', pinyin: 'xianggang' },
  { label: '雅安', pinyin: 'yaan' },
  { label: '延安', pinyin: 'yanan' },
  { label: '延边', pinyin: 'yanbian' },
  { label: '盐城', pinyin: 'yancheng' },
  { label: '阳江', pinyin: 'yangjiang' },
  { label: '阳泉', pinyin: 'yangquan' },
  { label: '扬州', pinyin: 'yangzhou' },
  { label: '烟台', pinyin: 'yantai' },
  { label: '宜宾', pinyin: 'yibin' },
  { label: '益阳', pinyin: 'yiyang' },
  { label: '宜昌', pinyin: 'yichang' },
  { label: '宜春', pinyin: 'yichun' },
  { label: '营口', pinyin: 'yingkou' },
  { label: '鹰潭', pinyin: 'yingtan' },
  { label: '伊春', pinyin: 'yichun' },
  { label: '伊犁', pinyin: 'yili' },
  { label: '银川', pinyin: 'yinchuan' },
  { label: '玉林', pinyin: 'yulin' },
  { label: '榆林', pinyin: 'yulin' },
  { label: '运城', pinyin: 'yuncheng' },
  { label: '云浮', pinyin: 'yunfu' },
  { label: '玉树', pinyin: 'yushu' },
  { label: '玉溪', pinyin: 'yuxi' },
  { label: '岳阳', pinyin: 'yueyang' },
  { label: '永州', pinyin: 'yongzhou' },
  { label: '枣庄', pinyin: 'zaozhuang' },
  { label: '张家口', pinyin: 'zhangjiakou' },
  { label: '张家界', pinyin: 'zhangjiajie' },
  { label: '张掖', pinyin: 'zhangye' },
  { label: '湛江', pinyin: 'zhanjiang' },
  { label: '肇庆', pinyin: 'zhaoqing' },
  { label: '昭通', pinyin: 'zhaotong' },
  { label: '郑州', pinyin: 'zhengzhou' },
  { label: '中山', pinyin: 'zhongshan' },
  { label: '中卫', pinyin: 'zhongwei' },
  { label: '舟山', pinyin: 'zhoushan' },
  { label: '珠海', pinyin: 'zhuhai' },
  { label: '漳州', pinyin: 'zhangzhou' },
  { label: '周口', pinyin: 'zhoukou' },
  { label: '驻马店', pinyin: 'zhumadian' },
  { label: '株洲', pinyin: 'zhuzhou' },
  { label: '淄博', pinyin: 'zibo' },
  { label: '自贡', pinyin: 'zigong' },
  { label: '资阳', pinyin: 'ziyang' },
  { label: '遵义', pinyin: 'zunyi' },
]

export interface CityLetterGroup {
  letter: string
  cities: CityDirectoryEntry[]
}

function firstLetter(entry: CityDirectoryEntry) {
  const initial = entry.pinyin.charAt(0).toUpperCase()
  return initial >= 'A' && initial <= 'Z' ? initial : '#'
}

// 按拼音首字母分组，组内按拼音排序（目录为手工维护，不依赖文件顺序）。
export function groupCityDirectory(entries: CityDirectoryEntry[] = CITY_DIRECTORY): CityLetterGroup[] {
  const groups = new Map<string, CityDirectoryEntry[]>()
  for (const entry of entries) {
    const letter = firstLetter(entry)
    const bucket = groups.get(letter)
    if (bucket) {
      bucket.push(entry)
    }
    else {
      groups.set(letter, [entry])
    }
  }
  return [...groups.entries()]
    .sort(([a], [b]) => (a === '#' ? 1 : b === '#' ? -1 : a.localeCompare(b)))
    .map(([letter, cities]) => ({
      letter,
      cities: [...cities].sort((a, b) => a.pinyin.localeCompare(b.pinyin) || a.label.localeCompare(b.label, 'zh-Hans-CN')),
    }))
}

export function cityIndexOfLabel(label: string) {
  return CITY_DIRECTORY.findIndex(entry => entry.label === label)
}

// 「搜索城市名/拼音」：城市名包含或整串拼音包含（不区分大小写）。
export function filterCityDirectory(term: string, entries: CityDirectoryEntry[] = CITY_DIRECTORY) {
  const keyword = term.trim().toLowerCase()
  if (!keyword) {
    return entries
  }
  return entries.filter(entry => entry.label.includes(keyword) || entry.pinyin.includes(keyword))
}
